### ISSUE TITLE
No integration at Configuration > Integrations visible

### ISSUE THREAD

**Issue by chaoscrack** [siku2/hass-weather-srgssr#1]
I did install the repository into the hacs and I can see it as a integration. Also I have the keys from the SRG website. But if I go to Configuration > Integrations there is no srg, ssr, meteo, weather or something like that.

What dit I wrong?
Thanks for help.

**Comment by siku2** [comment]
You probably dodged a bullet there. As mentioned at the top of the readme, the API this integration is based on has been deprecated and will, if it hasn't already, stop working in the future.

There is a new alternative API, but it doesn't offer the same features and a lot of work is required to adapt this integration.
